version: '3.4'

services:
  demohotellisting:
    image: ${DOCKER_REGISTRY-}demohotellisting
    build:
      context: .
      dockerfile: DemoHotelListing/Dockerfile
    ports:
      - 8085:80
      - 8086:443
