version: '3.4'

services:
  feedbackdb:
    image: mongo:latest
    container_name: "feedbackdb"
 #   networks:
  #    - bridge
    hostname: localhost
    ports:
      - 27017:27017

  feedbackservice:
    image: ${DOCKER_REGISTRY-}feedbackservice
    build:
      context: .
      dockerfile: FeedbackService/Dockerfile
 #   networks:
  #    - bridge
    hostname: localhost
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CampaignDatabase:ConnectionString=mongodb://feedbackdb:27017"
    depends_on:
      - feedbackdb
    ports:
      - 8090:80
      - 8095:443
    

#networks:
 # bridge:
    # Use a custom driver
  #  driver: bridge