version: "2"

services:
  mongodb-user:
    image: mongo:latest
    container_name: "mongodb-user"
    hostname: localhost
    ports:
      - 27017:27017

  feedback-service:
    container_name: feedback-service
    build: FeedbackService
    hostname: localhost
    network_mode: host
    ports:
      - 8080:80
    restart: always

