version: "2"

services:
  mongodb-user:
    image: mongo:latest
    container_name: "mongodb-user"
    hostname: localhost
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  user-service:
    container_name: user-service
    build: UserService
    hostname: localhost
    network_mode: host
    ports:
      - 8090:8090
    restart: always

  feedback-service:
    container_name: feedback-service
    build: FeedbackService
    hostname: localhost
    network_mode: host
    ports:
      - 8080:8080
    restart: always

